import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from '../components/Weather'
import Spinner from '../components/Spinner'
import Link from 'next/link';

export default function Home() {

  const[input, setInput] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  // trying to insert variables here breaks it for some reason
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${input}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      setErrorMessage('');
    }).catch(error => {
      setErrorMessage('- Invalid Input -');
    })
    setInput('')
    setLoading(false)
  }

  if(loading)
  {
    return <Spinner />
  }

  return (
    <div>
      <Head>
        <title>Athena Weather App | Ted Langlie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Overlay */}
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/20 z-[1] min-h-screen' />
      <Image src='https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80' 
      layout='fill'
      className='object-cover'
      />

      {/* Heading */}
        <div className='relative flex justify-between items-center max-w-[300px] w-full m-auto pt-4 text-7xl font-bold text-white z-10'>
        <Image
            src='/../public/assets/trident.png'
            alt='/'
            width='75'
            height='75'
        />
        
        <div className='left-10'>
        <h1>
          Athena
        </h1>
        </div>
        </div>


      {/* Search */}
      <div className='relative flex px-10 justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
          <form onSubmit={fetchWeather} className='flex justify-between items-center w-full m-auto p-3 bg-transparent border-4 border-white text-white rounded-2xl'>
            <div>
              <input 
              onChange={(e)=> setInput(e.target.value)}
              className='bg-transparent border-none text-white focus:outline-none text-2xl' type="text" placeholder='Search City or Country' 
              />
            </div>
            <button onClick={fetchWeather}><BsSearch size={35}/></button>
          </form>
      </div>

      {/* Error Message */}
      {errorMessage && (
        <p className='absolute left-1/2 transform -translate-x-1/2 text-red-400 z-10 font-bold'> {errorMessage} </p>
      )}

      {/* Weather */}
      {weather.main && <Weather data={weather}/>}
      
      {/* Footer */}
      <footer
        className="
              text-3xl text-white
              border-t-4 border-white
              absolute
              inset-x-0
              bottom-0
              p-4
              bg-gradient-to-r from-slate-500 via-teal-500 to-blue-500
              md:flex md:p-6">
              <p className="relative text-sm text-white z-10">© Ted Langlie || <a href="mailto:theodorelanglie@gmail.com" className="hover:underline text-blue-100">Contact me!</a>
          </p>
          <div className='relative flex'>
          <div className='relative text-white z-10'>
                      <Link href='https://www.linkedin.com/in/theodore-langlie-b75238240/'>
                          <li className='flex relative ml-10 text-sm uppercase hover:bg-blue-600 hover:rounded-md cursor-pointer'>
                          <Image
                              src='/../public/assets/Linkedin.png'
                              alt='/'
                              width='30'
                              height='30'
                          /> </li>
                      </Link>
          </div>
          <div className='relative text-white z-10'>
                      <Link href='https://github.com/TedLanglie'>
                          <li className='flex relative ml-10 text-sm uppercase hover:bg-blue-600 hover:rounded-md cursor-pointer'>
                          <Image
                              src='/../public/assets/github.png'
                              alt='/'
                              width='30'
                              height='30'
                          /> </li>
                      </Link>
          </div>
        </div>
      </footer>
      
    </div>
  )
}
